site_name: FaBo T-Display-S3 Docs
theme:
    name: material
    custom_dir: 'docs/theme'
    language: 'ja'
    palette:
      primary: 'yellow'
      accent: 'black'
    logo: 'logo.png'
    favicon: 'favicon.png'
extra:
    search:
        language: 'jp'
markdown_extensions:
  - fontawesome_markdown
  - pymdownx.highlight:
      use_pygments: true
      noclasses: false
      pygments_style: monokai
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.keys
  - attr_list
extra_css:
#  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
#  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
#  - "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css"
  - "css/version-select.css"
  - "css/custom.css"
nav:
  - Home: "index.md"
  - 初期の設定:
    - Arduino IDEの設定: "lilygo/setting.md"
  - 初期のサンプル:
    - 時計: "lilygo/clock.md"
  - Arduino:
    - Hello World: "arduino/helloworld.md"
    - ボタン: "arduino/button.md"
    - 円の描画: "arduino/circle.md"
    - 画面の切替: "arduino/screen.md"
    - 画像の描画: "arduino/image.md"
extra_javascript:
  - javascripts/version-select.js
  - javascripts/extra.js
plugins:
  - macros
